output "container_ids" {
  description = "Map of container IDs created by the Docker container module"
  value       = { for key, container in module.containers : key => container.container_id }
}

output "container_names" {
  description = "Map of container names created by the Docker container module"
  value       = { for key, container in module.containers : key => container.container_name }
}

output "xml_file_paths" {
  description = "Map of XML file paths generated by the Unraid XML module"
  value       = { for key, xml in module.containers_xml : key => xml.xml_file_path }
}

output "xml_file_contents" {
  description = "Map of XML file contents generated by the Unraid XML module"
  value       = { for key, xml in module.containers_xml : key => xml.xml_file_content }
}
